version: '3.8'
services:
  config-server-dev:
    image: 211020/cloud-config:latest
    container_name: config-server
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mh-config.cceyhlcvjfnk.us-east-1.rds.amazonaws.com:5432/mhconfig
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=5RQI9yPAExiQUy7gCaXX
      - SPRING_DATASOURCE_HIKARI_SCHEMA=mhmarket
    networks:
      - mh-network
    restart: unless-stopped
    dns:
      - 103.162.20.4
      - 8.8.8.8
networks:
  mh-network:
    driver: bridge
