version: '3.8'
services:
  config-server-dev:
    image: mhmarket/config:latest
    container_name: config-server
    environment:
      PORT: 8888
    ports:
      - "8888"
    network_mode: host
    dns:
      - 192.168.200.4
      - 8.8.8.8
networks:
  mhmarket-config-dev:
    driver: bridge
